name: CI

on:
  push: {}
  pull_request:
    types: [opened, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.23'
      - name: Pull Postgres
        run: docker pull postgres:14.0
      - name: Pull MariaDB
        run: docker pull mariadb:10.8
      - name: Pull SQLServer
        run: docker pull mcr.microsoft.com/mssql/server:2022-latest
      - name: Check go version
        run: go version
      - name: Run linters
        run: go vet ./... && go install honnef.co/go/tools/cmd/staticcheck@latest && bash -c "$(go env GOPATH)/bin/staticcheck ./..."
      - name: Run Tests Against current latest versions
        run: ./scripts/run-all-tests.sh
      - name: Run Tests Against current branch
        run: |
          cp go.work.example go.work
          ./scripts/run-all-tests.sh
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


